// image size = 966 x 638
const projects = [
  {
    name: "Street Style Landing Page",
    tech: "HTML and CSS",
    image: "/projects/project01.webp",
    code: "https://github.com/vishal-kumaar/Project-1-Street-Style-Landing-Page",
    live: "https://street-style-landing-site.vercel.app/",
    desc: "This is the static, good looking, and non-responsive website. The tech stack that I use to create this website is HTML and CSS.",
  },
  {
    name: "Food Restaurant Home Page",
    tech: "HTML and CSS",
    image: "/projects/project02.webp",
    code: "https://github.com/vishal-kumaar/Project-2-Food-Restaurant-Home-Page",
    live: "https://food-restaurant-home-site.vercel.app/",
    desc: "This is the static, good looking, and non-responsive website. The tech stack that I use to create this website is HTML and CSS.",
  },
  {
    name: "Digital Marketing Page",
    tech: "HTML and CSS",
    image: "/projects/project03.webp",
    code: "https://github.com/vishal-kumaar/Project-4-Digital-Marketing-Page",
    live: "https://digital-marketing-site.vercel.app/",
    desc: "This is the static, good looking, and non-responsive website. The tech stack that I use to create this website is HTML and CSS.",
  },
  {
    name: "Crypto Landing Page",
    tech: "HTML and CSS",
    image: "/projects/project04.webp",
    code: "https://github.com/vishal-kumaar/Project-5-Crypto-Landing-Page",
    live: "https://crypto-landing-site.vercel.app/",
    desc: "This is the static, good looking, and non-responsive website. The tech stack that I use to create this website is HTML and CSS.",
  },
  {
    name: "Plant Home Page",
    tech: "HTML and CSS",
    image: "/projects/project05.webp",
    code: "https://github.com/vishal-kumaar/Project-6-Plant-Home-Page",
    live: "https://plant-home-site.vercel.app/",
    desc: "This is the static, good looking, and non-responsive website. The tech stack that I use to create this website is HTML and CSS.",
  },
  {
    name: "Product Home Page",
    tech: "HTML and CSS",
    image: "/projects/project06.webp",
    code: "https://github.com/vishal-kumaar/Project-7-Product-Home-Page",
    live: "https://product-home-site.vercel.app/",
    desc: "This is the static, good looking, and responsive website. The tech stack that I use to create this website is HTML and CSS.",
  },
  {
    name: "Web Design Landing Page",
    tech: "HTML and CSS",
    image: "/projects/project07.webp",
    code: "https://github.com/vishal-kumaar/Project-8-Web-Design-Landing-Page",
    live: "https://web-design-landing-site.vercel.app/",
    desc: "This is the static, good looking, and responsive website. The tech stack that I use to create this website is HTML and CSS.",
  },
  {
    name: "Developer Landing Page",
    tech: "HTML and CSS",
    image: "/projects/project08.webp",
    code: "https://github.com/vishal-kumaar/Project-9-Developer-Landing-Page",
    live: "https://developer-landing-site.vercel.app/",
    desc: "This is the static, good looking, and responsive website. The tech stack that I use to create this website is HTML and CSS.",
  },
  {
    name: "Hosting Landing Page",
    tech: "HTML and CSS",
    image: "/projects/project09.webp",
    code: "https://github.com/vishal-kumaar/Project-11-Hosting-Landing-Page",
    live: "https://hosting-landing-site.vercel.app/",
    desc: "This is the static, good looking, and responsive website. The tech stack that I use to create this website is HTML and CSS.",
  },
  {
    name: "Interior Design Landing Page",
    tech: "HTML and CSS",
    image: "/projects/project10.webp",
    code: "https://github.com/vishal-kumaar/Project-10-Interior-Design-Landing-Page",
    live: "https://interior-design-landing-site.vercel.app/",
    desc: "This is the static, good looking, and responsive website. The tech stack that I use to create this website is HTML and CSS.",
  },
  {
    name: "Business Landing Page",
    tech: "HTML and CSS",
    image: "/projects/project11.webp",
    code: "https://github.com/vishal-kumaar/Project-12-Business-Landing-Page",
    live: "https://business-landing-site.vercel.app/",
    desc: "This is the static, good looking, and responsive website. The tech stack that I use to create this website is HTML and CSS.",
  },
  {
    name: "SAAS Landing Page",
    tech: "HTML and CSS",
    image: "/projects/project12.webp",
    code: "https://github.com/vishal-kumaar/Project-13-SAAS-Landing-Page",
    live: "https://saas-landing-site.vercel.app/",
    desc: "This is the static, good looking, and responsive website. The tech stack that I use tp create this website is HTML and CSS.",
  },
  {
    name: "Rock Paper Scissor",
    tech: "HTML, CSS, and JavaScript",
    image: "/projects/project13.webp",
    code: "https://github.com/vishal-kumaar/Rock-Paper-Scissors",
    live: "https://saas-landing-site.vercel.app/",
    desc: "This is a very popular game and we must have played it at least once in our life. This website is also responsive also means we can use this in any size of device. The tech stack I use to create this website is HTML, CSS, and JavaScript.",
  },
  {
    name: "Food delivery static site",
    tech: "HTML and CSS",
    image: "/projects/project14.webp",
    code: "https://github.com/vishal-kumaar/food-delivery-website-template",
    live: "https://vishal-kumaar.github.io/food-delivery-website-template/",
    desc: "This is the static, good looking, and responsive food delivery dummy website template. The tech stack that I use tp create this website is HTML and CSS.",
  },
  {
    name: "Shade Up",
    tech: "HTML, CSS, and JavaScript",
    image: "/projects/project15.webp",
    code: "https://github.com/vishal-kumaar/Shade-Up",
    live: "https://shadeup.vercel.app/",
    desc: "This is the static, good looking, and responsite website. This website have functionality such as color convertor, see color by RGB range, see color by HEX code, generate random color, etc. The tech stack that I use to create this website is HTML, CSS, and JavaScript.",
  },
  {
    name: "Product Design Landing Page",
    tech: "HTML and CSS",
    image: "/projects/project16.webp",
    code: "https://github.com/vishal-kumaar/Project-15-Project-Design-Landing-Page",
    live: "https://design-landing-site.vercel.app/",
    desc: "This is a static, good looking and responsive website. The tech stack that I use to create this website is HTML and CSS.",
  },
  {
    name: "Rode Clone",
    tech: "HTML and TailwindCSS",
    image: "/projects/project17.webp",
    code: "https://github.com/vishal-kumaar/Rode-Clone-TailwindCSS",
    live: "https://vishal-kumaar.github.io/Rode-Clone-TailwindCSS/",
    desc: "This is the homepage clone of the Rode's website. This is the static, good looking, and responsite website. The tech stack that I use to create this website is HTML and Tailwind CSS",
  },
  {
    name: "Paytm Clone",
    tech: "HTML and TailwindCSS",
    image: "/projects/project18.webp",
    code: "https://github.com/vishal-kumaar/Paytm-Clone-TailwindCSS",
    live: "https://vishal-kumaar.github.io/Paytm-Clone-TailwindCSS/",
    desc: "This is the homepage clone of the Paytn's website. This is the static, good looking, and responsite website. The tech stack that I use to create this website is HTML and Tailwind CSS",
  },
  {
    name: "Shopify Clone",
    tech: "HTML and TailwindCSS",
    image: "/projects/project19.webp",
    code: "https://github.com/vishal-kumaar/Shopify-Clone-TailwindCSS",
    live: "https://vishal-kumaar.github.io/Shopify-Clone-TailwindCSS/",
    desc: "This is the homepage clone of the Shopify's website. This is the static, good looking, and responsite website. The tech stack that I use to create this website is HTML and Tailwind CSS",
  },
  {
    name: "Calculator",
    tech: "ReactJs and Taiwind CSS",
    image: "/projects/project20.webp",
    code: "https://github.com/vishal-kumaar/react-calculator",
    live: "https://calcmaster.vercel.app/",
    desc: "This is the static, good looking, and responsive calculator website. This calculator is only for simple mathematical operation such as Addition, Subtraction, Multiplication, and Division. This website also have dark mode theme. The tech stack that I use to create this calculator is ReactJs and Taiwlind CSS",
  },
  {
    name: "Magic Notes",
    tech: "MERN Stack and Tailwind CSS",
    image: "/projects/project21.webp",
    code: "https://github.com/vishal-kumaar/magic-notes",
    live: "https://magicnotes.up.railway.app/",
    desc: "This is the dynamic, good looking, and responsive note making web application. This website have many functionalities such as dark mode, user login, user signup, forgotten password, update/reset password, create note, edit note, check note, search note, delete note, etc. The tech stack that I use to create this note making web application is MongoDb, ExpressJs, ReactJs, NodeJs, and Tailwind CSS.",
  },
  {
    name: "Personal Portfolio",
    tech: "ReactJs, NextJs, and Tailwind CSS",
    image: "/projects/project22.webp",
    code: "https://github.com/vishal-kumaar/personal-portfolio",
    live: "https://vishalkumar.vercel.app/",
    desc: "This is static, good looking, and responstive portfolio site. The tech stack that I use to create this portfolio site is ReactJs, NextJs, and Tailwind CSS",
  },
  {
    name: "Movies Picker",
    tech: "ReactJs, NextJs, Tailwind CSS, Axios and TMDB API",
    image: "/projects/project23.webp",
    code: "https://github.com/vishal-kumaar/moviespicker",
    live: "https://movies-picker.vercel.app/",
    desc: "This is the dynamic, good looking, and responsive movies and tv series picking application. This website have many functionalities such as explore different catagories of movie/series, see details related to any movie/series (such as cast, crew, videos, budget, revenue, original language, etc.), search any movie, series and personality related to film industary, get personalized movies or tv series related to your favorite genre, etc. The tech stack that I use to create this movies picker application is ReactJs, NextJs, Tailwind CSS, Axios, and TMDB API.",
  },
].reverse();

export default projects;
